apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.common.namespace }}
  labels:
    app: {{ .Values.serviceMonitor.serviceSelector }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.todoapp.labelName }}
  ports:
  - protocol: TCP
    {{- with .Values.service }}
    name: http
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    {{- end }}
